    CREATE TABLE olympics_athletes_events (
    id INT,
    name VARCHAR(100),
    sex CHAR(1),
    age INT,
    height INT,
    weight INT,
    team VARCHAR(100),
    noc CHAR(3),
    games VARCHAR(20),
    year INT,
    season VARCHAR(10),
    city VARCHAR(50),
    sport VARCHAR(50),
    event VARCHAR(100),
    medal VARCHAR(20)
);

INSERT INTO olympics_athletes_events (id, name, sex, age, height, weight, team, noc, games, year, season, city, sport, event, medal) VALUES
(3520, 'Guillermo J. Amparan', 'M', NULL, NULL, NULL, 'Mexico', 'MEX', '1924 Summer', 1924, 'Summer', 'Paris', 'Athletics', 'Athletics Men''s 800 metres', NULL),
(35394, 'Henry John Finchett', 'M', NULL, NULL, NULL, 'Great Britain', 'GBR', '1924 Summer', 1924, 'Summer', 'Paris', 'Gymnastics', 'Gymnastics Men''s Rings', NULL),
(21918, 'Georg Frederik Ahrensborg Clausen', 'M', 28, NULL, NULL, 'Denmark', 'DEN', '1924 Summer', 1924, 'Summer', 'Paris', 'Cycling', 'Cycling Men''s Road Race Individual', NULL),
(110345, 'Marinus Cornelis Dick Sigmond', 'M', 26, NULL, NULL, 'Netherlands', 'NED', '1924 Summer', 1924, 'Summer', 'Paris', 'Football', 'Football Men''s Football', NULL),
(54193, 'Thodore Tho Jeitz', 'M', 26, NULL, NULL, 'Luxembourg', 'LUX', '1924 Summer', 1924, 'Summer', 'Paris', 'Gymnastics', 'Gymnastics Men''s Individual All-Around', NULL),
(23240, 'Charles Barney Cory', 'M', 47, 180, NULL, 'United States', 'USA', '1904 Summer', 1904, 'Summer', 'St. Louis', 'Golf', 'Golf Men''s Individual', NULL),
(85019, 'Nicolaas Johannes Nederpeld', 'M', 37, NULL, NULL, 'Netherlands', 'NED', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Individual', NULL),
(25934, 'Jan Johannes de Blcourt', 'M', 47, NULL, NULL, 'Netherlands', 'NED', '1908 Summer', 1908, 'Summer', 'London', 'Shooting', 'Shooting Men''s Free Pistol 50 yards', NULL),
(35191, 'John Charles Field-Richards', 'M', 29, NULL, NULL, 'Gyrinus-1', 'GBR', '1908 Summer', 1908, 'Summer', 'London', 'Motorboating', 'Motorboating Mixed B-Class (Under 60 Feet)', 'Gold'),
(4073, 'Andreac', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(120786, 'Pierre Tolar', 'M', NULL, NULL, NULL, 'Luxembourg', 'LUX', '1924 Summer', 1924, 'Summer', 'Paris', 'Gymnastics', 'Gymnastics Men''s Rings', NULL),
(33723, 'August Oliver Gus Fager (Fagerstrm-)', 'M', 32, 178, 61, 'United States', 'USA', '1924 Summer', 1924, 'Summer', 'Paris', 'Athletics', 'Athletics Men''s Cross-Country Team', 'Silver'),
(82480, 'Mosso', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(18257, 'Gustaf Vilhelm Carlberg', 'M', 44, NULL, NULL, 'Sweden', 'SWE', '1924 Summer', 1924, 'Summer', 'Paris', 'Shooting', 'Shooting Men''s Rapid-Fire Pistol 25 metres', 'Silver'),
(27874, 'Destin Destine', 'M', NULL, NULL, NULL, 'Haiti', 'HAI', '1924 Summer', 1924, 'Summer', 'Paris', 'Shooting', 'Shooting Men''s Free Rifle 400 600 and 800 metres Team', 'Bronze'),
(5831, 'Sidney James Montford Sid Atkinson', 'M', 23, 186, 76, 'South Africa', 'RSA', '1924 Summer', 1924, 'Summer', 'Paris', 'Athletics', 'Athletics Men''s 110 metres Hurdles', 'Silver'),
(72917, 'Jaroslav Mach', 'M', 37, NULL, NULL, 'Czechoslovakia', 'TCH', '1924 Summer', 1924, 'Summer', 'Paris', 'Shooting', 'Shooting Men''s Free Rifle 400 600 and 800 metres Team', NULL),
(97418, 'Edmund John Pueschel', 'M', 21, NULL, NULL, 'United States', 'USA', '1904 Summer', 1904, 'Summer', 'St. Louis', 'Gymnastics', 'Gymnastics Men''s Individual All-Around Apparatus Work', NULL),
(49768, 'Dora Honnywill (Neve-)', 'F', 37, NULL, NULL, 'Great Britain', 'GBR', '1908 Summer', 1908, 'Summer', 'London', 'Archery', 'Archery Women''s Double National Round', NULL),
(63311, 'Jan Koutn', 'M', 26, NULL, NULL, 'Czechoslovakia', 'TCH', '1924 Summer', 1924, 'Summer', 'Paris', 'Gymnastics', 'Gymnastics Men''s Rope Climbing', NULL),
(81214, 'Englebert Mollin', 'M', NULL, NULL, NULL, 'Belgium', 'BEL', '1924 Summer', 1924, 'Summer', 'Paris', 'Wrestling', 'Wrestling Men''s Lightweight Greco-Roman', NULL),
(26259, 'Louis Verrant Gabriel Le Bailly de la Falaise', 'M', 42, NULL, NULL, 'France', 'FRA', '1908 Summer', 1908, 'Summer', 'London', 'Fencing', 'Fencing Men''s Sabre Individual', NULL),
(100458, 'Leslie George Rich', 'M', 21, NULL, NULL, 'United States', 'USA', '1908 Summer', 1908, 'Summer', 'London', 'Swimming', 'Swimming Men''s 100 metres Freestyle', NULL),
(25585, 'Henry D. Davids', 'M', NULL, NULL, NULL, 'Great Britain', 'GBR', '1908 Summer', 1908, 'Summer', 'London', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(66696, 'Lucien lie Larg (Barreau-)', 'M', 26, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Masters Individual', NULL),
(47952, 'Helmer Hermansen', 'M', 29, NULL, NULL, 'Norway', 'NOR', '1900 Summer', 1900, 'Summer', 'Paris', 'Shooting', 'Shooting Men''s Free Rifle Kneeling 300 metres', NULL),
(129248, 'Karl Magnus Wegelius', 'M', 23, NULL, NULL, 'Finland', 'FIN', '1908 Summer', 1908, 'Summer', 'London', 'Gymnastics', 'Gymnastics Men''s Team All-Around', 'Bronze'),
(25610, 'Charles C. Davies', 'M', NULL, NULL, NULL, 'Great Britain', 'GBR', '1908 Summer', 1908, 'Summer', 'London', 'Athletics', 'Athletics Men''s 400 metres', NULL),
(13249, 'tienne Bonnes', 'M', 29, 172, 76, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Rugby', 'Rugby Men''s Rugby', 'Silver'),
(2723, 'Gaston Jules Louis Antoine Alibert', 'M', 22, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(19198, 'Ernst Christensen', 'M', 24, NULL, NULL, 'Denmark', 'DEN', '1908 Summer', 1908, 'Summer', 'London', 'Gymnastics', 'Gymnastics Men''s Team All-Around', 'Gold'),
(36270, 'Charles Hardy', 'M', 33, NULL, NULL, 'Great Britain', 'GBR', '1908 Summer', 1908, 'Summer', 'London', 'Athletics', 'Athletics Men''s Hammer Throw', NULL),
(63450, 'Jan Kowalczk', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(27994, 'Carlo de Marchi', 'M', NULL, NULL, NULL, 'Italy', 'ITA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Masters Individual', NULL),
(83683, 'Jean Albert Edmond Muller', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(136072, 'Etienne van Zuylen', 'M', NULL, NULL, NULL, 'Belgium', 'BEL', '1900 Summer', 1900, 'Summer', 'Paris', 'Croquet', 'Croquet Men''s Singles One Ball', NULL),
(67877, 'Leon Henry Albin Darrien', 'M', 42, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Sabre', NULL),
(42915, 'Constantin Henrik Johan Godard', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Sabre', NULL),
(127465, 'Erik Verner Lidberg', 'M', 30, 167, 68, 'Sweden', 'SWE', '1924 Summer', 1924, 'Summer', 'Paris', 'Wrestling', 'Wrestling Men''s Heavyweight Greco-Roman', NULL),
(50672, 'Marcel Hansen', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(80618, 'Andr Moulonguet', 'M', NULL, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Individual', NULL),
(26371, 'Gerhard Boettcher', 'M', 30, NULL, NULL, 'Germany', 'GER', '1924 Summer', 1924, 'Summer', 'Paris', 'Athletics', 'Athletics Men''s 3000 metres Steeplechase', NULL),
(35831, 'Joseph Fendt', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(57031, 'Mihaly Kalman Karikopulos', 'M', NULL, NULL, NULL, 'Greece', 'GRE', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Foil', NULL),
(20471, 'Georges Valentin Hubrecht', 'M', 32, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(128885, 'Louis van Heijninghen van Beze', 'M', NULL, NULL, NULL, 'Netherlands', 'NED', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(60950, 'Valentin Ledoux', 'M', 23, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(137678, 'Carl Christian Wilsgaard', 'M', 31, 169, 70, 'Norway', 'NOR', '1924 Summer', 1924, 'Summer', 'Paris', 'Wrestling', 'Wrestling Men''s Heavyweight Greco-Roman', NULL),
(45868, 'Raymonde Durand-Mougeot', 'F', 30, 160, 51, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Croquet', 'Croquet Mixed Doubles', NULL),
(41120, 'Landon Giles', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(112963, 'Tore Holm', 'M', 34, NULL, NULL, 'Sweden', 'SWE', '1924 Summer', 1924, 'Summer', 'Paris', 'Sailing', 'Sailing Men''s 8 metres', 'Gold'),
(34053, 'Arthur Otto Vivian Edwards', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(41219, 'Emile van Isselstein', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Sabre', NULL),
(130634, 'Adolf Lindfors', 'M', 40, 183, 105, 'Finland', 'FIN', '1924 Summer', 1924, 'Summer', 'Paris', 'Wrestling', 'Wrestling Men''s Heavyweight Greco-Roman', 'Gold'),
(40492, 'Jean Garreta', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Sabre', NULL),
(62504, 'Hassan Bekkali', 'M', 23, 162, 62, 'Morocco', 'MAR', '1924 Summer', 1924, 'Summer', 'Paris', 'Boxing', 'Boxing Men''s Lightweight', NULL),
(12467, 'tienne Begouin', 'M', 27, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Individual', NULL),
(4405, 'Alibert', 'M', NULL, NULL, NULL, 'France', 'FRA', '1900 Summer', 1900, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Masters Sabre', NULL),
(4081, 'Andr Charles Louis Alexandre Amadieu', 'M', 27, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Individual', NULL),
(3452, 'Paul Renaud Baudry d''Asson', 'M', 25, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s epee Individual', NULL),
(124827, 'Georgios Tsitas', 'M', 23, 162, 59, 'Greece', 'GRE', '1924 Summer', 1924, 'Summer', 'Paris', 'Wrestling', 'Wrestling Men''s Lightweight Greco-Roman', NULL),
(25640, 'Jacques Beny', 'M', NULL, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Fencing', 'Fencing Men''s Foil Individual', NULL),
(138690, 'Edwin Morris Wright', 'M', 22, NULL, NULL, 'United States', 'USA', '1924 Summer', 1924, 'Summer', 'Paris', 'Athletics', 'Athletics Men''s 400 metres', 'Bronze'),
(51683, 'Pierre Hompesch', 'M', 23, NULL, NULL, 'France', 'FRA', '1924 Summer', 1924, 'Summer', 'Paris', 'Gymnastics', 'Gymnastics Men''s Parallel Bars', NULL)
