-- Create the table
CREATE TABLE fb_users (
    id INT,
    name VARCHAR(50),
    joined_at DATE,
    city_id INT,
    device INT
);

-- Insert the data
INSERT INTO fb_users (id, name, joined_at, city_id, device) VALUES
(4, 'Ashley Sparks', '2020-06-30', 63, 2185),
(8, 'Zachary Tucker', '2018-02-18', 78, 3900),
(9, 'Caitlin Carpenter', '2020-07-23', 60, 8592),
(18, 'Wanda Ramirez', '2018-09-28', 55, 7904),
(21, 'Tonya Johnson', '2019-12-02', 62, 4816),
(24, 'Carlos Newman', '2020-02-06', 74, 861),
(25, 'Natasha Bradford', '2020-02-12', 60, 9401),
(27, 'Jessica Farrell', '2019-03-24', 67, 7190),
(32, 'Catherine Hurst', '2018-08-22', 51, 5529),
(33, 'Amanda Leon', '2017-10-06', 77, 4597),
(34, 'Donald Ross', '2017-10-14', 54, 1239),
(37, 'Michael Turner', '2018-04-01', 74, 1041),
(41, 'Donna Walker', '2017-10-05', 70, 1586),
(46, 'Tracy Hunter', '2019-08-10', 51, 2936),
(50, 'Samuel Miller', '2020-07-24', 50, 666),
(52, 'Michelle Jimenez', '2019-02-19', 66, 7393),
(56, 'Theresa Weaver', '2019-11-05', 72, 8209),
(58, 'Rhonda Davis', '2018-08-25', 79, 3822),
(78, 'Zachary Anderson', '2019-02-15', 71, 5696),
(82, 'Jacob York', '2020-08-21', 75, 540),
(87, 'David Taylor', '2019-05-11', 75, 7120),
(89, 'Kyle Curry', '2018-05-18', 56, 2054),
(95, 'Robert Little', '2020-07-27', 54, 383),
(99, 'Ryan Howe', '2018-08-18', 52, 9036);



-- Create the table
CREATE TABLE fb_comments (
    user_id INT,
    body TEXT,
    created_at DATE
);

-- Insert the data
INSERT INTO fb_comments (user_id, body, created_at) VALUES
(89, 'Wrong set challenge guess college as position.', '2020-01-16'),
(33, 'Interest always door health military bag. Store smile factor player goal detail TV loss.', '2019-12-31'),
(34, 'Physical along born key leader various. Forward box soldier join.', '2020-01-08'),
(46, 'Kid must energy south behind hold. Research common long state get at issue. Weight technology live plant. His size approach loss.', '2019-12-29'),
(25, 'Or matter will turn only woman fact.', '2019-12-21'),
(8, 'Western east tax group character establish professor. Forward growth material. Before garden military product. Over southern manager. Along series civil theory force language clear.', '2020-01-13'),
(18, 'Difficult town soon. Though alone race fine customer certain task. Field body adult. Behind nation require. Garden after believe.', '2020-02-03'),
(32, 'Per measure course why poor write identify. Quality fear sometimes lead. One a past seven attack. Sometimes usually where ten figure picture thank. Stock rather color order attention paper.', '2020-01-10'),
(82, 'Cold bag ago surface head at key. Experience former concern down still stand. Wind reflect dinner art enjoy. Doctor inside read. Raise here she.', '2019-12-30'),
(58, 'Though training policy any. Step past major. Because gun agency model. Analysis information news month choice herself consumer.', '2020-02-02'),
(78, 'Increase girl threat student. Weight law dream education significant interview possible. Worry investment thing. Other describe create full personal. Model sit thank site military right.', '2020-01-07'),
(87, 'Star talk little main long usually mean environment. Bag president baby expect environmental capital experience. Baby their live.', '2019-12-25'),
(18, 'Knowledge man memory child analysis. Evening while about month. Have answer because every. Scene those tree behind pressure debate small.', '2019-12-27'),
(89, 'Arm when officer technology walk door television same. Table national later actually. Parent system indeed quite.', '2020-02-12'),
(9, 'Blood upon notice reduce. Order these size technology among majority. Floor nice art herself. Cold above condition leave market us health phone.', '2020-01-06'),
(27, 'School finally sit building southern. Them for course participant. Yard meet list almost language. Feeling item record. Take yard around music. Simple former side finish study fact forward.', '2020-01-10'),
(56, 'Best concern decision seek. Determine wrong suggest hospital remember small. Thank firm gun now. Protect record bar west sound kind power. Every floor news test candidate.', '2019-12-25'),
(99, 'President natural open before affect natural per. Type keep section nearly her often yet staff. Line public either fight. Country enough various article why. Finally east buy stay government.', '2020-02-03'),
(41, 'Call house customer force her movie skill. Leader trial seat. Everybody question watch. Challenge service test heavy window western. Sit father mouth garden certainly there.', '2020-01-03'),
(37, 'Organization left season consumer majority white. Public result next action send individual guess. Artist new blue maybe western act cost who.', '2020-02-01'),
(52, 'Especially bank recently cause. Be better care career argue occur trial almost. Note trial skill floor should candidate. Fact full individual federal others.', '2020-01-01'),
(4, 'Significant entire station order away. Man position adult tend. Here feeling energy wonder far piece. Seven production all. Building military police third he truth without.', '2020-02-15'),
(21, 'Person party low. Watch detail full choice. Research enjoy listen choose area. Purpose perhaps source against through even recently.', '2019-12-28'),
(32, 'Heavy natural new turn sing level. Firm form mother skin. Determine environmental usually live.', '2019-12-18'),
(95, 'Success next stage student she she. History community minute miss. Say guess month worry organization he culture. Four research attention.', '2020-01-17'),
(78, 'Director offer strong nature. Usually now else middle box. Catch feel adult however. Page star already. Best realize against actually friend.', '2020-01-04'),
(24, 'Career bring these environment network rest parent. Particularly guy big send town responsibility play. Move local fire number.', '2019-12-29'),
(50, 'Effect heart Mrs performance size house establish. Again tell involve will attack send. Common office read admit.', '2020-01-31'),
(32, 'Feeling reason story none. Recognize popular professor thousand compare hope. Firm same figure boy newspaper. Condition hope health might toward visit action wait.', '2020-01-06'),
(37, 'Billion fact learn enough director dream. Public on represent. Military very so throughout mouth. As should try perhaps history far sometimes. Police prevent science few assume each ten.', '2020-01-19'),
(89, 'Development just leader sit. None third your century box science test. Billion heavy tough card successful market. Bit red vote wall stuff relate heavy.', '2019-12-25'),
(33, 'Teacher too miss once commercial appear himself. Important ten full their prove issue sea. Accept role painting today. List tonight garden any accept everyone.', '2020-01-22'),
(34, 'Thousand field soldier minute. Half trade top ready me debate. Likely century protect material.', '2020-01-15'),
(46, 'Rich successful make line cultural real our. Road Mr star information responsibility past. Make compare enough public behavior.', '2019-12-23'),
(25, 'Subject base military fund by garden. Ready send alone experience anything member magazine military. Recognize buy career move might father.', '2020-02-14'),
(8, 'Part if investment religious what enter. During seek pay sister. Easy wear impact can. Anything career culture three newspaper here. Fast nature up allow end meeting especially.', '2020-01-22'),
(18, 'Just measure check me treat. True today particular help significant writer. Fast hear what movement mention check prove.', '2019-12-17'),
(32, 'Player road it security. Cover meet capital give stop own. Second wife race miss four anyone there. Eye seek exist six science side.', '2020-01-17'),
(82, 'Truth rock play radio language. Heart should left fire. Court trial because or. People smile pretty against seat such. Behind thank begin occur.', '2020-01-23'),
(58, 'Again morning usually herself sort fast. Ten general food above foot economy. My yes seven style. Together change oil race wish research. Girl policy or defense new write term.', '2020-01-26'),
(78, 'Wonder bring ability sense also model through. Policy heavy look remember sure star. Case meeting visit face red. Measure pay prepare. Charge them effort letter. Poor pressure certain across hair.', '2020-02-15'),
(4, 'Artist position sit according. Bill school side billion unit outside word town. Measure west sea discuss book different budget.', '2020-01-01'),
(87, 'Foot company nothing face where east. Behind level edge article us marriage. Bag need language. Responsibility marriage central. Social radio specific million realize price.', '2020-01-08'),
(18, 'Peace computer lay pick report available. Fast imagine today voice feeling effort his. Seem growth notice first. Save commercial be program example.', '2019-12-30'),
(89, 'Beat lay lead group week fall successful. Job however for particularly government store wife control. Why professional however structure rate none door station.', '2020-01-07'),
(9, 'Key sort case difference choice team although. Concern usually where program decade. Establish concern none artist run others.', '2020-02-02'),
(27, 'Skin nice occur recent. All particular total participant them theory able. Myself commercial amount class article source. Training individual process two not. Shake go what person wife system.', '2020-01-25'),
(56, 'Also financial reach inside worker difference stand. Eat create perform single serious role. Perform including week degree century energy.', '2019-12-19'),
(99, 'Name piece somebody year. Wish since evening police. Throw series candidate rock. New nature sure manager window once. Activity author fact.', '2020-01-05'),
(41, 'Ask factor important else nothing. Detail group lead account page ask unit. Simple else standard trial. Land attorney score.', '2019-12-27'),
(37, 'Worker teach understand tough. Anyone off community. Almost much safe tell enjoy positive.', '2019-12-15'),
(52, 'Life modern life during security name take. Beat operation contain modern machine allow. Although cold leader hit.', '2019-12-20'),
(4, 'Glass various box feeling pattern sometimes. Too alone throughout outside why professional left. Country agency information every difficult.', '2019-12-22'),
(21, 'Value either total create popular. Something position school camera. Hand so store them front owner. Economic city compare middle student.', '2020-01-06'),
(32, 'Allow respond draw enter behavior baby career. Course she film out research sound. Around machine play change sit term.', '2020-01-10'),
(95, 'Contain fire when economic soldier local growth stage. Will floor skin want so dog couple season. Plant people recently page fact.', '2020-02-01'),
(78, 'Ten everyone senior election protect. Fine star concern prevent site base view. City information resource example. Control agree final forward. Work action eight share process building region.', '2020-01-30'),
(24, 'Activity material job person nothing heavy million energy. Guess house especially we cup attorney. Star happy carry level all attorney program.', '2019-12-31'),
(50, 'Event next charge building southern same including. Surface commercial throughout former raise page mouth.', '2019-12-28'),
(32, 'Fire condition along physical career million ready. Test natural truth. Blood affect current candidate scene campaign hit. Investment wife technology describe truth source.', '2020-02-01');
